### ISSUE TITLE
i cannot find the etage method

### ISSUE THREAD

**Issue by ioslide** [afsharshamsi/ETAGE#1]
can u provide me a path

**Comment by afsharshamsi** [comment]
can you please elaborate more on your issue? if you meant you cannot find the method in the code, please have a look at line 541 of test.py which runs the code in etage mode. if you meant you need the checkpoints/saved-models to run the code, i can provide you with a shared folder.

**Comment by ioslide** [comment]
@afsharshamsi 
Thank you ! I solved it

**Comment by afsharshamsi** [comment]
Great
